# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NimStrikesBack_white.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from cupol import starter

nim = 'Ним наносит ответный удар:' if starter.language == 'rus' else 'Nim strikes back'
cur = 'Текущее число:' if starter.language == 'rus' else 'Current number:'
move = 'Осталось ходов:' if starter.language == 'rus' else 'Moves left:'


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(281, 199)
        Form.setStyleSheet(
            "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(218, 218, 218, 255));")
        self.now_number_label = QtWidgets.QLabel(Form)
        self.now_number_label.setGeometry(QtCore.QRect(39, 153, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.now_number_label.setFont(font)
        self.now_number_label.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.now_number_label.setObjectName("now_number_label")
        self.minus_button = QtWidgets.QPushButton(Form)
        self.minus_button.setGeometry(QtCore.QRect(180, 50, 90, 31))
        self.minus_button.setStyleSheet("QPushButton{\n"
                                        "border: 3px solid #b7b7b7;\n"
                                        "border-radius: 10px;\n"
                                        "background-color: none;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: #c8c8c8;\n"
                                        "}")
        self.minus_button.setText("")
        self.minus_button.setObjectName("minus_button")
        self.plus_button = QtWidgets.QPushButton(Form)
        self.plus_button.setGeometry(QtCore.QRect(10, 50, 90, 31))
        self.plus_button.setStyleSheet("QPushButton{\n"
                                       "border: 3px solid #b7b7b7;\n"
                                       "border-radius: 10px;\n"
                                       "background-color: none;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "background-color: #c8c8c8;\n"
                                       "}")
        self.plus_button.setText("")
        self.plus_button.setObjectName("plus_button")
        self.result_label = QtWidgets.QLabel(Form)
        self.result_label.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.result_label.setFont(font)
        self.result_label.setStyleSheet("background: none;\n"
                                        "border-radius: 10px;\n"
                                        "border: 3px solid #b7b7b7;\n"
                                        "")
        self.result_label.setText("")
        self.result_label.setObjectName("result_label")
        self.ostatok_label = QtWidgets.QLabel(Form)
        self.ostatok_label.setGeometry(QtCore.QRect(39, 103, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.ostatok_label.setFont(font)
        self.ostatok_label.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.ostatok_label.setObjectName("ostatok_label")
        self.ostatok_qlcd = QtWidgets.QLabel(Form)
        self.ostatok_qlcd.setGeometry(QtCore.QRect(180, 100, 71, 31))
        self.ostatok_qlcd.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
                                        "border-radius: 10px;\n"
                                        "border: 3px solid #b7b7b7;\n"
                                        "")
        self.ostatok_qlcd.setText("")
        self.ostatok_qlcd.setObjectName("ostatok_qlcd")
        self.now_number_qlcd = QtWidgets.QLabel(Form)
        self.now_number_qlcd.setGeometry(QtCore.QRect(180, 150, 71, 31))
        self.now_number_qlcd.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
                                           "border-radius: 10px;\n"
                                           "border: 3px solid #b7b7b7;\n"
                                           "")
        self.now_number_qlcd.setText("")
        self.now_number_qlcd.setObjectName("now_number_qlcd")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", f"{nim}"))
        self.now_number_label.setText(_translate("Form", f"{cur}"))
        self.ostatok_label.setText(_translate("Form", f"{move}"))
