# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from cupol import Cupol

starter = Cupol()

class Ui_RegisterPage(object):
    def setupUi(self, RegisterPage):
        RegisterPage.setObjectName("RegisterPage")
        RegisterPage.resize(375, 635)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        RegisterPage.setFont(font)
        RegisterPage.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(218, 218, 218, 255));")
        self.centralwidget = QtWidgets.QWidget(RegisterPage)
        self.centralwidget.setObjectName("centralwidget")
        self.welcome_label = QtWidgets.QLabel(self.centralwidget)
        self.welcome_label.setGeometry(QtCore.QRect(50, 30, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(14)
        self.welcome_label.setFont(font)
        self.welcome_label.setStyleSheet("background-color: none")
        self.welcome_label.setObjectName("welcome_label")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(48, 213, 152, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password_label.setFont(font)
        self.password_label.setStyleSheet("background-color: none")
        self.password_label.setObjectName("password_label")
        self.remember_box = QtWidgets.QCheckBox(self.centralwidget)
        self.remember_box.setGeometry(QtCore.QRect(239, 412, 21, 20))
        self.remember_box.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.remember_box.setText("")
        self.remember_box.setObjectName("remember_box")
        self.remember_label = QtWidgets.QLabel(self.centralwidget)
        self.remember_label.setGeometry(QtCore.QRect(50, 405, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(14)
        self.remember_label.setFont(font)
        self.remember_label.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.remember_label.setObjectName("remember_label")
        self.login_line = QtWidgets.QLineEdit(self.centralwidget)
        self.login_line.setEnabled(True)
        self.login_line.setGeometry(QtCore.QRect(49, 154, 280, 40))
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(16)
        self.login_line.setFont(font)
        self.login_line.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.login_line.setStyleSheet("background: rgba(239,237,237,1);\n"
"border-radius: 10px;\n"
"border: 3px solid #b7b7b7;")
        self.login_line.setInputMethodHints(QtCore.Qt.ImhNone)
        self.login_line.setInputMask("")
        self.login_line.setText("")
        self.login_line.setMaxLength(32767)
        self.login_line.setReadOnly(False)
        self.login_line.setObjectName("login_line")
        self.password_line = QtWidgets.QLineEdit(self.centralwidget)
        self.password_line.setEnabled(True)
        self.password_line.setGeometry(QtCore.QRect(49, 248, 231, 40))
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(16)
        self.password_line.setFont(font)
        self.password_line.setAutoFillBackground(False)
        self.password_line.setStyleSheet("background: rgba(239,237,237,1);\n"
"border-radius: 10px;\n"
"border: 3px solid #b7b7b7;\n"
"")
        self.password_line.setText("")
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.password_line.setReadOnly(False)
        self.password_line.setObjectName("password_line")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(50, 310, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("background-color: none")
        self.name_label.setObjectName("name_label")
        self.hide_password_button = QtWidgets.QPushButton(self.centralwidget)
        self.hide_password_button.setGeometry(QtCore.QRect(288, 248, 41, 40))
        self.hide_password_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hide_password_button.setStyleSheet("QPushButton{\n"
"border: 3px solid #b7b7b7;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #c8c8c8;\n"
"}")
        self.hide_password_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hide_password_button.setIcon(icon)
        self.hide_password_button.setIconSize(QtCore.QSize(33, 33))
        self.hide_password_button.setObjectName("hide_password_button")
        self.register_button = QtWidgets.QPushButton(self.centralwidget)
        self.register_button.setGeometry(QtCore.QRect(205, 458, 125, 41))
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(7)
        self.register_button.setFont(font)
        self.register_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.register_button.setStyleSheet("QPushButton{\n"
"border: 3px solid #b7b7b7;\n"
"border-radius: 10px;\n"
"background-color: none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #c8c8c8;\n"
"}")
        self.register_button.setObjectName("register_button")
        self.name_line = QtWidgets.QLineEdit(self.centralwidget)
        self.name_line.setEnabled(True)
        self.name_line.setGeometry(QtCore.QRect(49, 342, 280, 40))
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(16)
        self.name_line.setFont(font)
        self.name_line.setStyleSheet("background: rgba(239,237,237,1);\n"
"border-radius: 10px;\n"
"border: 3px solid #b7b7b7;")
        self.name_line.setText("")
        self.name_line.setReadOnly(False)
        self.name_line.setObjectName("name_line")
        self.login_label = QtWidgets.QLabel(self.centralwidget)
        self.login_label.setGeometry(QtCore.QRect(50, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(14)
        self.login_label.setFont(font)
        self.login_label.setStyleSheet("background-color: none")
        self.login_label.setObjectName("login_label")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(49, 458, 125, 41))
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(18)
        self.login_button.setFont(font)
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_button.setStyleSheet("QPushButton{\n"
"border: 3px solid #b7b7b7;\n"
"border-radius: 10px;\n"
"background-color: none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #c8c8c8;\n"
"}")
        self.login_button.setObjectName("login_button")
        RegisterPage.setCentralWidget(self.centralwidget)
        # if starter.color == 'black':
        #     RegisterPage.setStyleSheet(
        #         "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(26, 53, 24, 255), stop:0.663158 rgba(35, 35, 35, 255));;")
        #     self.name_line.setStyleSheet("background: #070e0b;\n"
        #                                   "border-radius: 10px;\n"
        #                                   "border: 3px solid #20603D;\n"
        #                                   "color: #A5A5A5")
        #     self.password_line.setStyleSheet("background: #070e0b;\n"
        #                                   "border-radius: 10px;\n"
        #                                   "border: 3px solid #20603D;\n"
        #                                   "color: #A5A5A5")
        #     self.login_line.setStyleSheet("background: #070e0b;\n"
        #                                   "border-radius: 10px;\n"
        #                                   "border: 3px solid #20603D;\n"
        #                                   "color: #A5A5A5")
        #     self.register_button.setStyleSheet("QPushButton{\n"
        #     "border: 3px solid #20603D;\n"
        #     "border-radius: 10px;\n"
        #     "background-color: rgba(0, 0, 0, 0);\n"
        #     "color: #A5A5A5;\n"
        #     "}\n"
        #     "QPushButton:hover{\n"
        #     "background-color: #1E5945;\n"
        #     "}")
        #     self.login_button.setStyleSheet("QPushButton{\n"
        #     "border: 3px solid #20603D;\n"
        #     "border-radius: 10px;\n"
        #     "background-color: rgba(0, 0, 0, 0);\n"
        #     "color: #A5A5A5;\n"
        #     "}\n"
        #     "QPushButton:hover{\n"
        #     "background-color: #1E5945;\n"
        #     "}")
        #     self.hide_password_button.setStyleSheet("QPushButton{\n"
        #     "border: 3px solid #20603D;\n"
        #     "border-radius: 10px;\n"
        #     "background-color: rgba(0, 0, 0, 0);\n"
        #     "}\n"
        #     "QPushButton:hover{\n"
        #     "background-color: #1E5945;\n"
        #     "}")
        #     self.welcome_label.setStyleSheet("background-color: rgba(0,0,0,0);\n"
        #                                   "color: #A5A5A5;")
        #     self.password_label.setStyleSheet("background-color: rgba(0,0,0,0);\n"
        #                                   "color: #A5A5A5;")
        #     self.login_label.setStyleSheet("background-color: rgba(0,0,0,0);\n"
        #                                   "color: #A5A5A5;")
        #     self.name_label.setStyleSheet("background-color: rgba(0,0,0,0);\n"
        #                                   "color: #A5A5A5;")

        self.retranslateUi(RegisterPage)
        QtCore.QMetaObject.connectSlotsByName(RegisterPage)

    def retranslateUi(self, RegisterPage):
        _translate = QtCore.QCoreApplication.translate
        RegisterPage.setWindowTitle(_translate("RegisterPage", "Register"))
        self.welcome_label.setText(_translate("RegisterPage", "Добро пожаловать в Cupol"))
        self.password_label.setText(_translate("RegisterPage", "Пароль:"))
        self.login_line.setPlaceholderText(_translate("RegisterPage", "Логин"))
        self.password_line.setPlaceholderText(_translate("RegisterPage", "Пароль"))
        self.name_label.setText(_translate("RegisterPage", "Имя:"))
        self.register_button.setText(_translate("RegisterPage", "Зарегестрироваться"))
        self.name_line.setPlaceholderText(_translate("RegisterPage", "Имя"))
        self.login_label.setText(_translate("RegisterPage", "Логин:"))
        self.login_button.setText(_translate("RegisterPage", "Войти"))
        self.remember_label.setText(_translate("RegisterPage", "Запомнить меня"))