# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginPage(object):
    def setupUi(self, LoginPage):
        LoginPage.setObjectName("LoginPage")
        LoginPage.resize(375, 635)
        LoginPage.setFixedSize(375, 635)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        LoginPage.setFont(font)
        LoginPage.setStyleSheet(
            "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(218, 218, 218, 255));")
        self.centralwidget = QtWidgets.QWidget(LoginPage)
        self.centralwidget.setObjectName("centralwidget")
        self.welcome_label = QtWidgets.QLabel(self.centralwidget)
        self.welcome_label.setGeometry(QtCore.QRect(55, 50, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(14)
        self.welcome_label.setFont(font)
        self.welcome_label.setStyleSheet("background-color: none")
        self.welcome_label.setObjectName("welcome_label")
        self.login_line = QtWidgets.QLineEdit(self.centralwidget)
        self.login_line.setEnabled(True)
        self.login_line.setGeometry(QtCore.QRect(49, 154, 280, 40))
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(16)
        self.login_line.setFont(font)
        self.login_line.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.login_line.setStyleSheet("background: rgba(239,237,237,1);\n"
                                      "border-radius: 10px;\n"
                                      "border: 3px solid #b7b7b7;")
        self.login_line.setInputMethodHints(QtCore.Qt.ImhNone)
        self.login_line.setInputMask("")
        self.login_line.setText("")
        self.login_line.setMaxLength(32767)
        self.login_line.setReadOnly(False)
        self.login_line.setObjectName("login_line")
        self.password_line = QtWidgets.QLineEdit(self.centralwidget)
        self.password_line.setEnabled(True)
        self.password_line.setGeometry(QtCore.QRect(49, 248, 231, 40))
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(16)
        self.password_line.setFont(font)
        self.password_line.setAutoFillBackground(False)
        self.password_line.setStyleSheet("background: rgba(239,237,237,1);\n"
                                         "border-radius: 10px;\n"
                                         "border: 3px solid #b7b7b7;\n"
                                         "")
        self.password_line.setText("")
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.password_line.setReadOnly(False)
        self.password_line.setObjectName("password_line")
        self.hide_password_button = QtWidgets.QPushButton(self.centralwidget)
        self.hide_password_button.setGeometry(QtCore.QRect(288, 248, 41, 40))
        self.hide_password_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hide_password_button.setStyleSheet("QPushButton{\n"
                                                "border: 3px solid #b7b7b7;\n"
                                                "border-radius: 10px;\n"
                                                "}\n"
                                                "QPushButton:hover{\n"
                                                "background-color: #c8c8c8;\n"
                                                "}")
        self.hide_password_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hide_password_button.setIcon(icon)
        self.hide_password_button.setIconSize(QtCore.QSize(33, 33))
        self.hide_password_button.setObjectName("hide_password_button")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(49, 342, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(18)
        self.login_button.setFont(font)
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_button.setStyleSheet("QPushButton{\n"
                                        "border: 3px solid #b7b7b7;\n"
                                        "border-radius: 10px;\n"
                                        "background-color: none;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color: #c8c8c8;\n"
                                        "}")
        self.login_button.setObjectName("login_button")
        LoginPage.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginPage)
        QtCore.QMetaObject.connectSlotsByName(LoginPage)

    def retranslateUi(self, LoginPage):
        _translate = QtCore.QCoreApplication.translate
        LoginPage.setWindowTitle(_translate("LoginPage", "Logib"))
        self.welcome_label.setText(_translate("LoginPage", "С возвращением в Cupol"))
        self.login_line.setPlaceholderText(_translate("LoginPage", "Логин"))
        self.password_line.setPlaceholderText(_translate("LoginPage", "Пароль"))
        self.login_button.setText(_translate("LoginPage", "Войти"))
