# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SimplePlanner_dark.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from cupol import starter

add = 'Добавить событие' if starter.language == 'rus' else 'Add'
planer = 'Минипланировщик' if starter.language == 'rus' else 'Simple Planner'


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 415)
        MainWindow.setFixedSize(668, 415)
        MainWindow.setStyleSheet(
            "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(26, 53, 24, 255), stop:0.663158 rgba(35, 35, 35, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 320, 348, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background: rgba(0,0,0,0);\n"
                                    "border-radius: 10px;\n"
                                    "border: 3px solid #20603D;\n"
                                    "color: #b7b7b7;\n"
                                    "")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(10, 10, 348, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.timeEdit.setFont(font)
        self.timeEdit.setStyleSheet("background: rgba(0,0,0,0);\n"
                                    "border-radius: 10px;\n"
                                    "border: 3px solid #20603D;\n"
                                    "color: #b7b7b7;\n"
                                    "")
        self.timeEdit.setObjectName("timeEdit")
        self.addEventBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addEventBtn.setGeometry(QtCore.QRect(10, 360, 348, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addEventBtn.setFont(font)
        self.addEventBtn.setStyleSheet("QPushButton{\n"
                                       "border: 3px solid #20603D;\n"
                                       "border-radius: 10px;\n"
                                       "background-color: none;\n"
                                       "color: #b7b7b7;;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "background-color: #1E5945;\n"
                                       "}")
        self.addEventBtn.setObjectName("addEventBtn")
        self.eventList = QtWidgets.QListWidget(self.centralwidget)
        self.eventList.setGeometry(QtCore.QRect(370, 10, 291, 381))
        self.eventList.setStyleSheet("background: rgba(0,0,0,0);\n"
                                     "border-radius: 10px;\n"
                                     "border: 3px solid #20603D;\n"
                                     "color: #b7b7b7;\n"
                                     "")
        self.eventList.setObjectName("eventList")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setEnabled(True)
        self.calendarWidget.setGeometry(QtCore.QRect(4, 40, 351, 271))
        self.calendarWidget.setMouseTracking(False)
        self.calendarWidget.setTabletTracking(False)
        self.calendarWidget.setAcceptDrops(False)
        self.calendarWidget.setAutoFillBackground(False)
        self.calendarWidget.setStyleSheet("  /*Tool button styles */\n"
                                          "QCalendarWidget QToolButton {\n"
                                          "height:40px;\n"
                                          "width:150px;\n"
                                          "color:#b7b7b7;\n"
                                          "font-size:20px;\n"
                                          "icon-size:56px,56px;\n"
                                          "background-color:#20603D;\n"
                                          "}\n"
                                          "  /* header row */\n"
                                          "QCalendarWidget  QWidget{\n"
                                          "alternate-background-color:rgb(128,128,128)\n"
                                          "}\n"
                                          "  /*normal days */\n"
                                          "QCalendarWidget QAbstractItemView:enabled {\n"
                                          "font-size:13px;\n"
                                          "color:rgb(180,180,180);\n"
                                          "background-color:#20603D;\n"
                                          "selection-background-color:#b7b7b7;\n"
                                          "selection-color:rgb(0,255,0);\n"
                                          "}")
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Минипланировщик"))
        self.addEventBtn.setText(_translate("MainWindow", f"{add}"))
