# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SimplePlanner_white.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from cupol import starter

add = 'Добавить событие' if starter.language == 'rus' else 'Add'
planer = 'Минипланировщик' if starter.language == 'rus' else 'Simple Planner'


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 402)
        MainWindow.setFixedSize(668, 415)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(4, 40, 351, 271))
        self.calendarWidget.setStyleSheet("")
        self.calendarWidget.setObjectName("calendarWidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 320, 348, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
                                    "border-radius: 10px;\n"
                                    "border: 3px solid #b7b7b7;\n"
                                    "")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(10, 10, 348, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.timeEdit.setFont(font)
        self.timeEdit.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
                                    "border-radius: 10px;\n"
                                    "border: 3px solid #b7b7b7;\n"
                                    "")
        self.timeEdit.setObjectName("timeEdit")
        self.addEventBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addEventBtn.setGeometry(QtCore.QRect(10, 360, 348, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addEventBtn.setFont(font)
        self.addEventBtn.setStyleSheet("QPushButton{\n"
                                       "border: 3px solid #b7b7b7;\n"
                                       "border-radius: 10px;\n"
                                       "background-color: none;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "background-color: #c8c8c8;\n"
                                       "}")
        self.addEventBtn.setObjectName("addEventBtn")
        self.eventList = QtWidgets.QListWidget(self.centralwidget)
        self.eventList.setGeometry(QtCore.QRect(370, 10, 291, 381))
        self.eventList.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
                                     "border-radius: 10px;\n"
                                     "border: 3px solid #b7b7b7;\n"
                                     "")
        self.eventList.setObjectName("eventList")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", f"{planer}"))
        self.addEventBtn.setText(_translate("MainWindow", f"{add}"))
